name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm
      - name: Install dependencies
        run: echo "Installing" && npm i
      - name: Build project
        run: echo "Running build" && npm run build
      - name: Run tests
        run: echo "Running tests" && npm run test
      - name: Upload artifact
        #   may need to update this action in the future https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
        uses: actions/upload-pages-artifact@v2
        with:
          # upload dist directory's content
          path: ./dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
